os: osx
language: c++
compiler: clang
osx_image: xcode7.3

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOSX_DEPLOYMENT_TARGET=10.9
    - secure: "RUqAX1NjBCoULDLA0f72rwB/0iMrab1LFW0knv9CWOg4d/cA6v1wfZPoi1HgVergY2cDhjq8TqDWTTTGgzOMiWm/ENoiSfBQy1VBdpX1PKquWR649rYfwfKvNFpmrUhGWMTv9D2VdCKYUgRHoz+/k8Iz4a796mTRK1aohLaQhdfU/YRpg5bahTWfCmBdKRG3AYAi7AwhtDkCvASEaTBCtuUIqwpfTyN3Cv9XY8gva5DR7GPlMFP1mbL+BxCdcv00R83KfZ4MwkFpvXRJBUJTTLLQzSy0zLMf6RK46jfGkR6tO7yC7QStKswQVd27EOhbksP7BlWfccBDeBqIdb0MJVoBlnh0CnB2gybPQI95xgXO6w4V1hOw3smCd5LtPfcWTkfg/L3W80ptgQPXOtgdO0kxI7ZQQ7bCK+JFYUMW+6Kvv4lW6i6UluaFCJsSGuF3Z63Guk5sD/q8dn4HYLtKhBcbkdf2RgckKDg2XZP3FQVoX9IRBcJWWcGq58eiuI2AsQpabvRaQSpXzuxDdZEyWmjE2osJ4K0jPFzxzZ/73Jkm2YuKvn7PGRFRXelBcFqJlczAw/r0WKofpN2mVv0hGDK71sCjtoV3eumfyvs1Y557UI3Z+Kw3gA4D9QjNAA5nOFtVwyhg27dqDWtScotUEN0edBa/UOWbIDXLIZ+kiy8="
    - secure: "DgUseODIYyx/lIl/KaNWzFud6s34g6hfYR9cizdbWND+CCrD5GX6BePMKnQ1VEOlHmHGEN22gySrA5HSeCl+sZuNjvJdm4mpno8pE6CqTMdNSkX3JMi6QJFs8w0ZXEMXUS2c5jSb4lUvroEE/wcPExNvDWzK4omU0rUoUawGUzbYKZ4tZs4Btv8nHyAOV4egVFx/najI7eCTXvlI0o5LqkRhUSE2fj9FS/jAiQF2twev9ggkVw3oIPjcZLWLkRUkdsVBdvvnbjLt85JF/wfUp383F41TFi8NSCiZQ0yll2GyVKP/PSSdqmjOPTLg3hrao5EjN04ySC7fPCCbw272LLjtj42a0e37RtTA8zRZr8Zm+cvshLZ/x3AI6eudfjeTWJ+qlOcmL0CSIaibZyRjLbgBhXI/J5+Z8h1GZAnQpNwo4i07JHToebOFNgom/plAt6DoWhmGuqwhxdjsHcXCTUViMG6jdpy0zvzNpy2cpGcgjh9WPu03z1OZWAkuva2wmvkvUmw7UvGf+07VtXraGxzkmCtXEMIij2xi0i01rKDJxM8eb8Sg7dgVacEwp7lHYnvA1wqDDI10T6s9W/dF0u+64C9jAB9BMVFuTxJQz0zU5bbLBoOpsCoDMXV/QsMVrOfr9PbJd4zOMg+an9CduBWpskiOK6os/mfiO3oWJdo="

branches:
  only:
  - master
  - /\d+\.\d+\.\d+(-\d+)?/

git:
  depth: 3

script:
  - echo "var = $GDRIVE_REFRESH_TOKEN"
  - brew install gdrive
  - gdrive --refresh-token $GDRIVE_REFRESH_TOKEN list
  - mkdir build && cd build
  - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ -DCMAKE_BUILD_TYPE=Release -DSKIP_FC_GUI=1 -DNO_TEST_EXE=1 ../
  - make -j4

deploy:
  provider: script
  script: bash ../appveyor_scripts/macdeploy.sh
  skip_cleanup: true
  on:
    branch: master

