os: osx
language: c++
compiler: clang
osx_image: xcode7.3

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOSX_DEPLOYMENT_TARGET=10.9
    - secure: "RczP8EtpjC5kkI5iNQmfyP9Uk1tWDHv3KSe1kKTzLOZmGKnlzRF3BECb6r86A3teiDFnnyikueMgCAbxMPZWIsFIEkLymvEvzsFDcdEEHGIkesnNLtJ9zR4FOXSquJapmtoK+zDfsTm+55rio5XGOIzoHda6rMScKenyzD0AT9IjGNZKXgI4LJgB/npem5vEZIoZMuEHpk5Vby4NUnLIS+tXvLgXsMNKteO/H8bFrfmMH4XBoFnFRgnfJS6R71eqlMiLhM8BBZW2Z6OHpDO/3hRaFvdddMT3EGFmHa6CnolGWjTGA5cArbCdrjRA9cNfrrFa9617zj5tNcTfmavWiuqXgnvEn5NfHWprQvx4H/RZ5P716rx5ZiEhOG1imIbYUZGm5/cYeAwedg77YugYrKMOHc+M33Fbe3UTERGSrrNKUk3Qf2RDzqIK96+RBOKblO7A9iYoKpEijvI2k6lOI3TlUPC7bv0HJV8AisWrjoDPfnKAb/gryV8x7GpYr4YX9ojUn3XRyjVlIedFLigMIoUWgX0U7zS8UFfasvXtVDqb9fEp803yvLhpAwS4RfhuHEaDHZ31hUJV8mgDtBToVB6gFcbRcp3GJImudZFmERzpRiGnmVOD/i5I20Z8gdOas1XVRrXkdK+0gPgoB9SF7JfmAg6xLw1imbkqpvahatE="
    - secure: "DgUseODIYyx/lIl/KaNWzFud6s34g6hfYR9cizdbWND+CCrD5GX6BePMKnQ1VEOlHmHGEN22gySrA5HSeCl+sZuNjvJdm4mpno8pE6CqTMdNSkX3JMi6QJFs8w0ZXEMXUS2c5jSb4lUvroEE/wcPExNvDWzK4omU0rUoUawGUzbYKZ4tZs4Btv8nHyAOV4egVFx/najI7eCTXvlI0o5LqkRhUSE2fj9FS/jAiQF2twev9ggkVw3oIPjcZLWLkRUkdsVBdvvnbjLt85JF/wfUp383F41TFi8NSCiZQ0yll2GyVKP/PSSdqmjOPTLg3hrao5EjN04ySC7fPCCbw272LLjtj42a0e37RtTA8zRZr8Zm+cvshLZ/x3AI6eudfjeTWJ+qlOcmL0CSIaibZyRjLbgBhXI/J5+Z8h1GZAnQpNwo4i07JHToebOFNgom/plAt6DoWhmGuqwhxdjsHcXCTUViMG6jdpy0zvzNpy2cpGcgjh9WPu03z1OZWAkuva2wmvkvUmw7UvGf+07VtXraGxzkmCtXEMIij2xi0i01rKDJxM8eb8Sg7dgVacEwp7lHYnvA1wqDDI10T6s9W/dF0u+64C9jAB9BMVFuTxJQz0zU5bbLBoOpsCoDMXV/QsMVrOfr9PbJd4zOMg+an9CduBWpskiOK6os/mfiO3oWJdo="

branches:
  only:
  - master
  - /\d+\.\d+\.\d+(-\d+)?/

git:
  depth: 3

script:
  - brew install gdrive
  - gdrive --refresh-token $GDRIVE_REFRESH_TOKEN list
  - mkdir build && cd build
  - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ -DCMAKE_BUILD_TYPE=Release -DSKIP_FC_GUI=1 -DNO_TEST_EXE=1 ../
  - make -j4

deploy:
  provider: script
  script: bash ../appveyor_scripts/macdeploy.sh
  skip_cleanup: true
  on:
    branch: master

