os: osx
language: c++
compiler: clang
osx_image: xcode7.3

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOSX_DEPLOYMENT_TARGET=10.9
    - secure: "RczP8EtpjC5kkI5iNQmfyP9Uk1tWDHv3KSe1kKTzLOZmGKnlzRF3BECb6r86A3teiDFnnyikueMgCAbxMPZWIsFIEkLymvEvzsFDcdEEHGIkesnNLtJ9zR4FOXSquJapmtoK+zDfsTm+55rio5XGOIzoHda6rMScKenyzD0AT9IjGNZKXgI4LJgB/npem5vEZIoZMuEHpk5Vby4NUnLIS+tXvLgXsMNKteO/H8bFrfmMH4XBoFnFRgnfJS6R71eqlMiLhM8BBZW2Z6OHpDO/3hRaFvdddMT3EGFmHa6CnolGWjTGA5cArbCdrjRA9cNfrrFa9617zj5tNcTfmavWiuqXgnvEn5NfHWprQvx4H/RZ5P716rx5ZiEhOG1imIbYUZGm5/cYeAwedg77YugYrKMOHc+M33Fbe3UTERGSrrNKUk3Qf2RDzqIK96+RBOKblO7A9iYoKpEijvI2k6lOI3TlUPC7bv0HJV8AisWrjoDPfnKAb/gryV8x7GpYr4YX9ojUn3XRyjVlIedFLigMIoUWgX0U7zS8UFfasvXtVDqb9fEp803yvLhpAwS4RfhuHEaDHZ31hUJV8mgDtBToVB6gFcbRcp3GJImudZFmERzpRiGnmVOD/i5I20Z8gdOas1XVRrXkdK+0gPgoB9SF7JfmAg6xLw1imbkqpvahatE="
    - secure: "otX7cbnEh1wESzZvu6eAKC4mQeDywDbZ+qubak4uXaiDvkTLC9xnl037XF/l7sBD3aFhEBGiWkEjNYkKC9xiKbcCEHHCpdAO1rj7tt2vnvgDIwrRBptzo6mdEugPexcqQEDym5qiApqcpV1K1FdD9ypKk5XzVky5xC7yEkavk1tvMAKoIUGtCW+gxZCtcpjxxGso4/5wdooCxuEHPZZEHNWCrXZEiH1GGSSkEqYko6CuS3koEkEXEtA6IK3WD55gt2N/9y9ibP8ofDDEXOBDBVoloBucTRL0OV5rxfdu1sZHUxaRMbLN2qU8F7cLZcmylbJ4rww0bFR2j+Up9VAOo5l9E+/7LyQDFBKkv3aEwp7frF5S1BJ9Md0HzZ4ajmf41PsFDGlVNnR/6XnisOmd9ET2CdRwBlbKIaAMbs2cZwvJ44jcJlef4UBGZCps1IXcUB6WkcdRyqlpEeyTUIB/Z5vjlV+TXK9lqyuQTQG8pL2fRpf1insvJ7yEQlhAzly2EpKWGvcXU46m2mQnuAtcRwq3nFx7aQKxVe88Xdt7OYmyM+znNdYxR7GjDhg5lm6s4MCIXea15hR4n7DhTzPlLwfAHOjaUNxJAk5J3BPMS5720iS41VeHfmY2hfuYb81/h9pSQmBoQI9ZKVYRPQNodm5oMIEBg9xFm0XCVvj8JZc="

branches:
  only:
  - master
  - /\d+\.\d+\.\d+(-\d+)?/

git:
  depth: 3

before_install:
  - brew install gdrive

script:
  - mkdir build && cd build
  - cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/ -DCMAKE_BUILD_TYPE=Release -DSKIP_FC_GUI=1 -DNO_TEST_EXE=1 ../
  - make -j4
  - $TRAVIS_BUILD_DIR/build/bin/flightcrew-plugin --version

after_success:
  - strip -u -r $TRAVIS_BUILD_DIR/build/bin/flightcrew-*


deploy:
  provider: script
  script: bash ../appveyor_scripts/macdeploy.sh
  skip_cleanup: true
  on:
    branch: master

